// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY99CEulvo_vJp6CEEdix5TSnk7wVm_ZU',
    appId: '1:871894860792:android:5a2587e5c4e2d67da7cc0d',
    messagingSenderId: '871894860792',
    projectId: 'chatapp-itsharks',
    storageBucket: 'chatapp-itsharks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE91q9uTNHrVOJr7uSF-dAAlv4hQqXtRA',
    appId: '1:871894860792:ios:b96f07908a1b990aa7cc0d',
    messagingSenderId: '871894860792',
    projectId: 'chatapp-itsharks',
    storageBucket: 'chatapp-itsharks.firebasestorage.app',
    androidClientId: '871894860792-9boq7e95q04v76kcvel1egv7tj5oroir.apps.googleusercontent.com',
    iosClientId: '871894860792-kr8icbk9f58autvpqcinbsnrpr2v08cp.apps.googleusercontent.com',
    iosBundleId: 'com.itSharks.chatApp',
  );

}